apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv3
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/vagrant/k8svolumes/mypv"
