apiVersion: v1
kind: Pod
metadata:
  name: host-path
spec:
  volumes:
    - name: html
      hostPath:
        path: /home/vagrant/nginx/html
        type: Directory
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: c2
      image: debian
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          date >> /html/index.html;
          sleep 5;
          done
